#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
rljdb wrapper script
"""

import sys
import os
from distutils.spawn import find_executable

BINDIR = os.path.abspath(os.path.dirname(__file__))
HISTORY_FILE="./rljdb.history";
RLWRAP_LOG_FILE="./rljdb.log";


if __name__ == '__main__':

    rlwrap = find_executable('rlwrap')
    if rlwrap is None: exit("Not found rlwrap")
    rljdb_filter = BINDIR + '/rljdb_filter'
    rlwrap_opts = ['-H', HISTORY_FILE,
                   '-l', RLWRAP_LOG_FILE,
                   '-w', '200',
                   #'-pRED',
                   '-pBLUE',
                   '-C', 'jdb',
                   '-b', "' .'",
                   '-z',
                   rljdb_filter]
    jdb = find_executable('jdb')
    jdb_opts = sys.argv[1:]
    cmd = [rlwrap] + rlwrap_opts + [jdb] + jdb_opts
    os.execvp(cmd[0], cmd)
