#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
"""

import sys
import os
#import io
#import types
#import struct
#import select
import re
#import traceback
#import binascii
#import collections
#import numbers
from distutils.spawn import find_executable

BINDIR = os.path.abspath(os.path.dirname(__file__))
HISTORY_FILE="./rljdb.history";
RLWRAP_LOG_FILE="./rljdb.log";

if __name__ == '__main__':

    rlwrap = find_executable('rlwrap')
    rljdb_filter = BINDIR + '/rljdb_filter'
    rlwrap_opts = ['-H', HISTORY_FILE,
                   '-l', RLWRAP_LOG_FILE,
                   '-w', '10',
                   '-pRED',
                   '-C', 'jdb',
                   '-b', "' .'",
                   '-z',
                   rljdb_filter]
    jdb = find_executable('jdb')
    jdb_opts = sys.argv[1:]

    cmd = [rlwrap]
    cmd.extend(rlwrap_opts)
    cmd.append('jdb')
    cmd.extend(jdb_opts)

    os.execvp(cmd[0], cmd)
